server:
  port: 8080

spring:
  profiles:
    active: "prod"
---
spring:
  profiles: dev

logging:
  level:
    .: ERROR
    org.springframework: ERROR
    com.schibsted: INFO

---
spring:
  profiles: test

server:
  port: 8080
  servlet:
    context-path: /v1

logging:
  level:
    .: ERROR
    org.springframework: INFO
    com.schibsted: INFO

---
spring:
  profiles: prod

server:
  port: 8080
  servlet:
    context-path: /v2

logging:
  level:
    .: ERROR
    org.springframework: INFO
    com.schibsted: INFO

